# Generated by Django 4.2.6 on 2023-10-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0002_category_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='Beginner', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappF23.course'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='student',
            field=models.ManyToManyField(to='myappF23.student'),
        ),
    ]
