# Generated by Django 4.2.6 on 2023-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0004_student_groups_student_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
