# Generated by Django 4.2.6 on 2023-11-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0005_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interested_courses',
            field=models.ManyToManyField(related_name='interested_students', to='myappF23.course'),
        ),
    ]
