# Generated by Django 4.2.6 on 2023-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0006_student_interested_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
