# Generated by Django 4.2.6 on 2023-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0008_alter_order_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
